# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-16 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20190515_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='博客主题'),
        ),
    ]
